snakemake-workflows/dna-seq-varlociraptor

README.md
workflow/rules/trimming.smk

Support to take samples from SRA instead of local files.

SRA-support

---

workflow/resources/igv-report-template.html
workflow/rules/ref.smk

This PR fixes the igv-report annotating genes and drugs instead of only drugs in the dgiDB column.

Fixed parsing of dgiDB drugs

---

workflow/resources/igv-report-template.html

This PR adds a linkout to clinicaltrials.gov

Added ClinicalTrials Linkout

---

.test/config/config.yaml
config/config.yaml
workflow/rules/common.smk
workflow/rules/trimming.smk
workflow/schemas/config.schema.yaml

Adding primer trimming by applying trimmomatic

Primer trimming

---

config/config.yaml
workflow/rules/common.smk
workflow/rules/tmb.smk
workflow/scripts/extract_primers_insert.py
workflow/scripts/render-scenario.py

This PR handles a change in the TMB functionality in varlociraptor and adds the `--plot-mode` parameter.

Added new tmb functionality from varlociraptor

---

workflow/envs/varlociraptor.yaml

Updates varlociraptor to v2.1 as this fixes a bug where filtering odds might omit some variants.

Updated varlociraptor

---

.test/config-sra/config.yaml
.test/config/config.yaml
.test/config_primers/config.yaml
config/config.yaml
workflow/rules/mapping.smk
workflow/rules/ref.smk

PR for integration of the GATK BaseRecalibratorSpark. This allows multi-threading and takes the applyBQSR step to its own rule.

Base recalibrator spark

---

workflow/schemas/config.schema.yaml

applyBQSR was not definied in config.schema.yaml.
This has been added.

Added bqsr to config schema

---

workflow/rules/common.smk
workflow/schemas/config.schema.yaml

Exactly what the title says (+ a schema fix).

Use vembrane table expression from config.yaml, if defined

---

.github/workflows/main.yml
workflow/resources/custom-table-report.js
workflow/rules/common.smk

As the binomial distribution could not be calculate for every variant, values are now being calculate in log-space as suggested by @tedil.
Since, the binomial coefficient turned out to be a limiting factor it is now approximated (see https://math.stackexchange.com/questions/64716/approximating-the-logarithm-of-the-binomial-coefficient).
Still, the other terms of the formula are also calculated in log space as these could become pretty small in case of a high coverage.

Approximate binomial distribution

---

workflow/envs/rbt.yaml

Bump rust-bio-tools version to 0.21.

Update rbt version

---

workflow/rules/common.smk

Exactly what the title says ;)

Allow #comments in samples.tsv and units.tsv

---

workflow/resources/custom-table-report.js

This adds linkouts for the varSEAK.

Added varSEAK linkouts

---

workflow/rules/common.smk
workflow/rules/regions.smk

Build regions using mosdepth

---

.test/config-chm-eval/scenario.yaml
.test/config-no-candidate-filtering/scenario.yaml
.test/config-sra/scenario.yaml
.test/config/scenario.yaml
.test/config_primers/scenario.yaml
config/scenario.yaml
workflow/envs/varlociraptor.yaml

(not sure what to tag this with, it's basically a `chore`, but then also a breaking change due to the scenario resolution changing)

feat!: update to varlociraptor 4.3

---

workflow/rules/candidate_calling.smk

This also fixes an issue with unsorted VCF records coming out of freebayes.

feat: update to latest freebayes and delly

---

.gitignore
workflow/rules/annotation.smk
workflow/rules/common.smk
workflow/rules/primers.smk

if-else closures spanning multiple rows are moved into methods in order to prevent misformatting by snakefmt.

move if-else closures

---

workflow/envs/varlociraptor.yaml
workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
workflow/rules/common.smk
workflow/rules/datavzrd.smk

This PR skips the onco- and variant-plots in the datavzrd-report when a batch only contains a single sample.

feat: render single sample

---

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
workflow/rules/common.smk
workflow/rules/datavzrd.smk
workflow/scripts/split-call-tables.py

feat: Remove plotdata from datavzrd template

---

workflow/Snakefile
workflow/envs/datavzrd.yaml
workflow/rules/benchmarking.smk
workflow/rules/calling.smk
workflow/rules/candidate_calling.smk
workflow/rules/common.smk
workflow/rules/mapping.smk
workflow/rules/primers.smk
workflow/rules/qc.smk
workflow/rules/ref.smk
workflow/rules/regions.smk

rename reference from "genome.fasta" to genome.{datatype}.{species}.{build}.{release}.fasta
rename sample.sorted.bam to sample.bam

feat: more informative file names

---

workflow/envs/varlociraptor.yaml

This enables:
1. definition of sexes other than female and male
2. fix for rare issues where the reported VAF did not match the most likely event

fix: update to varlociraptor 5.4.1

---

workflow/resources/datavzrd/spec_observations.json
workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
workflow/rules/common.smk
workflow/rules/datavzrd.smk
workflow/scripts/split-call-tables.py

Several fixes for the report:
- update datavzrd to 2.18.4
- fix varsome links: links are now build based on chromosome, position, alt and ref entries instead of HGVSg-value.
- added protein position and short protein alterations in details view
- adjusted angles for observation plots: plot labels might have overlapped when observations only exist on a single strand.

fix: several fixes

---

workflow/resources/datavzrd/data_observations.js
workflow/resources/datavzrd/spec_observations.json

This is the new observation plot, as a horizontal stacked bar plot, centered around the Equal (no evidence for either Ref or Alt) category. It provides checkboxes to provide separate rows for (combinations) of factor levels in the observation annotations `orientation`, `strand`, `mapping_quality`, and `edit_distance`.
For an interactive version to play around with the new plot, see [a respective GitHub Gist with the specification](https://gist.github.com/dlaehnemann/1dfb721a830cb9fdb158784cdfb2553a) or [directly in the interactive vega online editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQOJACckCCGgDaoWRrhoQbVTTizMSTO3lKmNWQBM0oBzgaYjsOFADWTNgAPEABfEIU9AyMITHUnRRBiJEEGQ3RY1IT7eNRXWXdPdG8-AOCwiJB9B …

feat: update observation plot to horizontal stacked bars with annotation variable checkbox

---

workflow/envs/varlociraptor.yaml
workflow/scripts/split-call-tables.py

Update for varlociraptor as it fixes an issue occuring when a record does not have an `ANN` field.

fix: update varlociraptor

---

workflow/envs/varlociraptor.yaml

This is waiting for varlociraptor 8.3 to land in Bioconda.

perf: update to varlociraptor 8.3

---

workflow/rules/trimming.smk

fixing a bug where errors did not occur in the log file

fix: update to latest cutadapt

---

workflow/resources/datavzrd/linkouts.js
workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
workflow/rules/datavzrd.smk

Linkouts have been refactored and added to non-coding variants in case required entries are existing.

feat: add linkouts to non-coding tables

---

.github/workflows/release-please.yml

Just a quick PR updating release-please to v4.

ci: Update release-please to v4
