snakemake-workflows/dna-seq-varlociraptor

workflow/scripts/oncoprint.R
This PR addresses an error where creating an oncoplot fails if there is only one sample.
=> Fixed minor bug in oncoprint

config/config.yaml
This PR adresses an issue where duplicate marking fails with an validation error.
This can be resolved by setting the validation stringency to `lenient`.
As this error occurred on every data set we processed @christopher-schroeder and I propose to set this as default parameter for the workflow.
=> Set default parameter for validation stringency

config/config.yaml, workflow/rules/common.smk, workflow/rules/trimming.smk
This PR addresses an issue (found by @jafors and @dlaehnemann) causing the workflow to break when applied to single end data.
This occurs while merging fastq files as a `read`-wildcard is expected.
=> Correct handling of single end data

workflow/rules/annotation/pass2.smk
This PR modifies the rule `dbnsfp_bgzip`:
Previously, data has been written to disk before being compressed to a gzip-file.
This has now been replaced by streaming data directly.
=> Stream data to gz-file

workflow/scripts/build_oncoprint_matrix.py
This PR fixes minor bug while building the oncoprint.
In cases where there is no gene annotated in a transcript the plot holds a row called 'X'.
To circumvent this transcripts without a gene annotation now get skipped.
=> Fixed minor bug

.test/config/config.yaml, config/config.yaml, workflow/Snakefile, workflow/envs/annotate_dgidb.yaml, workflow/envs/varlociraptor.yaml, workflow/rules/annotation/pass2.smk, workflow/rules/common.smk
This PR introduces the possible to create an igv-report as optional output.
As variant calling on WES- or WGS-data return many variants igv-reports may become to big to be opened in a file browser.
In case the report is disabled the workflow creates the fdr controled variants as a bcf-file.
=> Optional igv-reports

workflow/envs/snpeff.yaml, workflow/rules/annotation/pass1.smk
This PR adds a rule for downloading the snpEff database before annotating.
Previously the download was initiated by each snpEff annotation call.
This could lead to race conditions where each call downloads the database to the same temporary directory which got deleted after the first download finished.
=> Download snpEff database

workflow/rules/annotation.smk, workflow/rules/common.smk, workflow/rules/ref.smk, workflow/rules/utils.smk
This PR fixes an issue preventing snakemake to build the dag, as the output of rules `create_dbnsfp_tabix_index` and `tabix_known_variants` was undistinguishable.
=> Fix for ambiguous rules

workflow/envs/samtools.yaml, workflow/rules/ref.smk
This PR replaces Picardtools by samtools for generating the genome dictionary as Picardtools creates an empty one the call. The issue is further explained [here](https://github.com/snakemake-workflows/dna-seq-varlociraptor/issues/16).
Before merging wait until a test run has finished.
=> Replace Picard by samtools

workflow/rules/annotation.smk
This PR fixes the shell command executed by rule `extract_dbnfsp` failing as it contains a listing which return the exit status of the list.
Thanks to @tedil for solving this.
=> Fixed extract dbnfsp

config/config.yaml, workflow/rules/common.smk, workflow/rules/mapping.smk, workflow/rules/trimming.smk, workflow/schemas/config.schema.yaml
This PR contains two minor changes:
Cutadapt input is now places into a subfolder "sample/unit...". Using `-` as separator may confuse snakemake when deriving the wildcards.
Mark Duplicates is now optional and can now be changed in the config file.
=> Minor refinements

.test/config/config.yaml, config/config.yaml, workflow/envs/ptrimmer.yaml, workflow/rules/common.smk, workflow/rules/trimming.smk, workflow/schemas/config.schema.yaml
This PR replaces trimmomatic by ptrimmer, as trimming primers using trimmomatic did not work as expected.
Additionally I had to add pipes as pTrimmer asks for input files containing "_R1" and "_R2"-string in the file names.
=> Replace trimmomatic by ptrimmer

workflow/rules/trimming.smk
This PR fixes serveral issues causing ptrimmer to fail.
Fixes:
- Wrong output path where gzip can not find input file
- Missing `-s` parameter
- Concatenating of ptrimmer and gzip commands
Improvements:
- Higher compression rate
- Writing stdout and stderr to log-file
Current issues:
Currently files created by ptrimmer still exist after compression as writing to stdout keeps the original file. Does anyone know how to remove those without doing so manually?
Should we add two threads as there are two gzip processes?
More about it seems like `merge_fastqs` is called before both gzip processes have been finished as bwa crashes. The issue here is, that one of the merged fastq-mates has an unexpected `end-of-file` error while the the trimmed fastqs are fine. After deleting the merge fastqs the …
=> Fixing pTrimmer rules

workflow/envs/snpeff.yaml, workflow/rules/annotation.smk, workflow/rules/candidate_calling.smk
As the title says the rule `snpeff_download` get's replaced by the snpeff wrapper.
More about, the freebayes wrapper is updated to the latest version using a cleaner regex.
=> Replaced snpeff download by wrapper

workflow/resources/igv-report-template.html
Currently it happens that the final igv-report output file can not be rendered.
This mostly occurs if there are little variants and a empty column (not exists in the JSON-Table) is accessed. In this case the browser stops rendering returning an `data is undefined` error.
This can be handled by returning an empty string.
=> Fix igv-report rendering

workflow/rules/annotation.smk, workflow/rules/calling.smk, workflow/rules/candidate_calling.smk, workflow/rules/filtering.smk, workflow/rules/mapping.smk, workflow/rules/ref.smk, workflow/rules/utils.smk
This PR fixes the current workflow as `get_known_variants` fails due to a missing `build` parameter.
Additionally, all wrappers are updated to `0.55.1`.
=> Fix known variants

workflow/rules/common.smk, workflow/rules/utils.smk, workflow/scripts/build_target_regions.py
Currently, the workflow fails in case pairs of primers map to different chromosomes.
To fix this these primers are removed from the final bed file holding the targeted regions.
primers on different chromosomes are written tab-separated into the log holding information about primer name and both chromosomes.
=> Filter mapped primers

workflow/rules/mapping.smk, workflow/rules/ref.smk
Reverts snakemake-workflows/dna-seq-varlociraptor#44
Reason: on real data bwa-mem2 seems to stop unexpectedly early, without error message.
=> Revert "bwa-mem2" migration

workflow/rules/filtering.smk
This PR removes the rule `split_multi_alleles` as varlociraptor already outputs single allelic records.
=> Removed rule split_multi_alleles

workflow/rules/calling.smk, workflow/rules/common.smk
Currently the pipeline fails in case there are normal samples in addition to tumor samples.
This is due to a wrong input getter function and should be fixed now.
=> Fix input of varlociraptor preprocess for Tumor/Normal Samples

.github/workflows/main.yml, workflow/Snakefile, workflow/rules/calling.smk, workflow/rules/common.smk, workflow/rules/filtering.smk
Since introduction of the scattergather parallelization in this workflow, snakemake was unable to build the DAG due to a stackoverflow occurring because of a repeating wildcard, or more specifically: `{caller}` ended up as part of `{scatteritem}`, leading to the prefix "freebayes." being repeated over and over again. This PR should fix that.
This PR also unifies the use of `{ext}`, which now always has a leading dot in the patterns, i.e. `.{ext}`.
(I also had repeating `.sorted` suffixes, not sure which of these two changes fixed that.)
=> Bump snakemake min_version to 6.0.5

workflow/rules/common.smk, workflow/rules/report.smk
With the previous setup, including this rule via the new snakemake `module` syntax  and the `replace_prefix:` keyword will mean that the path specified in `input: bcfs=` gets prefixed, but the path manually provided in the `params: bcfs=` lambda expression does not. Thus the actual files specified on the command-line do not exist.
After the change, the file names from `input: bcfs=` are used directly and matched to the respective `group` with a params function with the arguments `wildcards` and `input`.
=> ensure that in `rule vcf_report` the bcf input file names are only defined once in `input:`

workflow/envs/bcftools.yaml, workflow/envs/bedtools.yaml, workflow/envs/htslib.yaml, workflow/envs/rbt.yaml, workflow/envs/samtools.yaml, workflow/envs/snpsift.yaml
bump versions of htslib dependent tools to 1.12, i.e. samtools, bcftools, htslib itself
=> Bump htslib versions

config/config.yaml, workflow/rules/primers.smk, workflow/schemas/samples.schema.yaml, workflow/schemas/units.schema.yaml
Set the primer trimming default configuration mode to autodetect primer library size (and error) with yara. Document that this is done by setting the `config.yaml` values to 0.
=> default to autodetect primer library size (and error) with yara + value docs

workflow/resources/custom-table-report.js
In rare cases rendering of the `rbt report` failed.
This occurs during building linkouts while either the gene-, transcriptID- or HGVSp-field is empty.
Linkouts will now be created based on available fields. If non of the fields exist the linkout-button won't be created.
This fixes: https://sharing.clickup.com/t/h/pfcbxv/K9AR1O8ZWFYY6NE
=> Handle empty annotation fields

workflow/rules/regions.smk
The recently added featur to only call regions with coverage leads to lots of freebayes invokes with short regions. This fix merges regions that are close to each other (< 15kb) and drastically reduces the runtime of freebayes by a factor of 40.
=> Merge closeby regions

workflow/rules/mapping.smk
When calculating duplicate reads it turns out that building the `extra`-param for marking duplicates fails due to a mistake when validating the truth value of a Pandas Series.
This has been fixed.
=> Fix parameter for mark_duplicates

workflow/resources/custom-table-report.js
It looks like the annotation field created by VEP has received a new value.
Therefore plots are failing as the index needs to be adjusted.
To prevent wrong indexing in the future it would probably help if `rbt vcf-report` saves the values of the ANN-field in a dictionary for directly accessing the correct values by name.
=> Fix vcf-report

workflow/rules/common.smk, workflow/rules/primers.smk
When mapping primers bowtie currently expects fastq-files as input.
In its current implementation the `-f` flag for accepting fasta files is only set for single primers.
This has been fixed.
Edit: As we have a testcase using fastq-primers both types are allowed now.
=> fix parameter for bowtie

.github/workflows/main.yml, workflow/envs/render_scenario.yaml, workflow/rules/calling.smk, workflow/rules/candidate_calling.smk, workflow/rules/plugins.smk, workflow/scripts/render-scenario.py
Original plan:
Use `gzip` instead of `bgzip` in `rule process_revel_scores:`, as `gzip` is commonly available in Linux, whereas `bgzip` is only available in the `htslib`. The alternative would be to add a conda environment to this rule, that installs `htslib`, but as all other commands are plain Linux tools, I would opt for the change proposed here. Also, I double-checked that the flag `-c` means the same thing in both (write to `stdout`).
Revised plan:
The file needs to be `bgzip`ed, as it is used with `tabix` downstream. And `tabix` doesn't deal in regular `gzip`.
=> actually load htslib for process_revel_scores (to have bgzip available)

workflow/envs/rbt.yaml, workflow/resources/custom-table-report.js, workflow/rules/common.smk, workflow/rules/plugins.smk, workflow/rules/utils.smk
This PR updates to rbt 0.39 which allows to access the index of ANN-field entries by field names.
Also the REVEL-plot will be fixed where values being benign or malign were flipped.
=> fix: custom-report: Replace indexes of ANN-field by keys

.github/workflows/main.yml, .test/config-target-regions/config.yaml, workflow/rules/mapping.smk
as a side-effect, this PR also turn two GitHub Action Test steps back on, that were previously skipped because all requested `.test/results` were still around from previous steps. These are now removed via a `stagein:` command. Also, we do not remove `.test/resources` in any of those `stagein:` commands any more, as that would be truly redundant testing of the resources download and processing.
=> fix: patch picard syntax usage

.gitignore, .test/config-chm-eval/config.yaml, .test/config-giab/config.yaml, .test/config-simple/config.yaml, config/config.yaml, workflow/rules/common.smk, workflow/rules/mapping.smk
As a side-effect, this also cleans up the `.gitignore` file a bit.
=> fix: picard syntax in configs and in the mark_duplicates rule

workflow/rules/regions.smk
Previously, the fasta index was only an implicit input requirement of the rule. Using a formal input file ensures, that snakemake can reason about it and provide a more useful error message (or rather an early fail).
=> fix: make the fasta index an explicit input of rule filter_group_regions

workflow/envs/datavzrd.yaml, workflow/envs/pandas.yaml, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/scripts/oncoprint.py
This PR fixes an issue where no value is returned when multiple samples are processed.
Additionally, when for some samples no variants were found this results in an invalid oncoprint table
This has been fixed by adding missing columns to the corresponding table.
Finally, the datavzrd template needed to be updated in order to handle optional linkout introduced by datavzrd.
=> fix: Handle multiple samples

workflow/rules/datavzrd.smk
This PR adjusts the input of `datavzrd_variants_calls` preventing `prepare_oncoprint` from being executed in case only a single sample is being analyzed.
=> fix: adjust input for datavzrd

workflow/envs/datavzrd.yaml, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/scripts/oncoprint.py
Currently the oncoprint in the datavzrd report has some short comings.
This includes multiple occurences of the same gene in the `gene_oncoprint` when different samples have variants on the same gene.
This will now be solved by joining these rows into a single one by merging the consequences of all samples.
In addition the variant oncoprint shows multiple rows for duplicated HGVSp values in case the HGVSg value differs.
In ordner to only show a single row per HGVSp value the HGVSg column will be hidden and the entries of HGVSp column are replaced by dropdown menus showing varsome-linkouts for each different HGVSg entry.
=> feat: enhance oncoprint report

workflow/rules/regions.smk
The filter group regions filters covered regions against a set of target regions if existing.
If the target regions file exists filtering is done by `bedtools intersect` defined by `{params.filter_targets}`.
In its current implementation the covered regions and target regions are being concatenated.
This way we would end up with the whole set of target regions but also duplicate entries.
=> fix: correctly filter target regions

workflow/rules/candidate_calling.smk, workflow/rules/regions.smk
This PR fixes an issue where freebayes gets an empty bed-file of covered regions.
The issue occurs in case the passed target-regions file contains chromosomal positions where the chromosome is denoted with a `chr`-prefix.
=> fix: Fix empty regions bed file

config/config.yaml
Currently the clinical significance is rendered twice in the datavzrd report.
Once as a malformated column named `CLIN_SIG` and another correctly formatted column with identical entries.
To reduce this redundancy the corresponding entry has been removed.
=> fix: remove clinical significance duplicate

workflow/rules/regions.smk
The workflow now fails with a message in case a empty bed file is created from custom target regions.
This might happen in case the custom file is invalid or empty.
=> fix: fail for empty target regions

workflow/rules/candidate_calling.smk
Candidate variants are currently called based on covered and, if provided, the intersection of target regions.
To reduce runtime close regions are getting merged.
As a consequence called variants can originate from off-target regions.
These are now getting eliminated by filtering the candidate calls by target regions if provided.
=> fix: Filter offtarget variants

workflow/envs/datavzrd.yaml, workflow/envs/oncoprint.yaml, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/common.smk, workflow/rules/datavzrd.smk, workflow/scripts/oncoprint.py
As a new feature reordnering rows in the gene oncoprint based on annotation labels has been added.
Rows are sorted by their statistical dependence on the selected annotation label.
Ordering is determined by the Chi² test which was previously implemented in the dna-seq-benchmark pipline (see [collect-fp-fn.py](https://github.com/snakemake-workflows/dna-seq-benchmark/blob/7a00a2fc7b722a66e6670f220e035ee46133a7bf/workflow/scripts/collect-fp-fn.py#L84)) and served as a template.
=> feat: Ordering gene oncoprint rows based on annotation label

config/config.yaml, workflow/rules/candidate_calling.smk, workflow/rules/common.smk, workflow/rules/regions.smk
As the currently implementation of excluding regions for delly may be to strict excluded regions are now handled differently.
Excluded regions can now be defined in the config-file setting `exclude_regions` in the `calling/delly` section.
In case the option is not set a predefined template file will be downloaded from `https://github.com/dellytools/delly/tree/main/excludeTemplates` if existing for the definied species and build.
If neither a custom region file is set nor a predefined template exists delly will be called without excluding regions.
=> feat: Set excluded regions for delly

workflow/resources/datavzrd/data_short_observations.js, workflow/resources/datavzrd/spec_observations.json, workflow/resources/datavzrd/spec_short_observations.json, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/common.smk, workflow/rules/datavzrd.smk
In addition to the observation plot in detail view the simple observations will be also plotted as horizontal bar plot.
There have also been some fixes and improvements to the extended observation plot:
- Barplot segments are now descending ordered by evidence starting with `Very strong`.
- the `Barely` segment was missing in previous plots causing a gap without tooltip
=> feat: Plot simple observations

workflow/rules/candidate_calling.smk, workflow/rules/common.smk
This is the quick fix for #216 . For the more thorough fix in snakemake-wrapper-utils, we should keep that issue open and I'll document what to do over there.
=> fix: require bcf index as input to rule filter_offtarget_variants

workflow/rules/common.smk
In the previous PR vembrane was updated to v1.0 including a breaking change where the syntax auf aux-arguments was changed from a whitespace to a `=`.
This was not considered and has been fixed now.
=> fix: fix vembrane aux

workflow/envs/varlociraptor.yaml, workflow/resources/datavzrd/data_observations.js, workflow/resources/datavzrd/data_short_observations.js, workflow/resources/datavzrd/spec_observations.json, workflow/resources/datavzrd/spec_short_observations.json, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/common.smk, workflow/scripts/split-call-tables.py
This adds support for varlociraptor 8.0 short observations and regular observation fields.
In case of short observations (`SAOBS` and `SROBS`) ref and alt alleles columns are being joined in order to be processable by datavzrd.
For the common `OBS`-field the edit distance is now being considered.
=> feat: Support new varlociraptor 8.0 observations

workflow/envs/snpsift.yaml
Due to an outdated version of SnpSift it may happen that some variants are getting lost when being annotated.
This issue seems to be fixed in the latest version of SnpSift.
=> fix: preserve lost variants

workflow/rules/common.smk
In case of callsets not having any filters `vembrane table` fails as the records of input bcf file have no annotation fields.
To fix this the input for fdr-control needs to be changed to the annotated bcf file.
=> fix: use annotated calls for unfiltered callsets

.test/config-target-regions/config.yaml, .test/config-target-regions/config_multiple_beds.yaml, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/common.smk, workflow/rules/ref.smk, workflow/scripts/oncoprint.py, workflow/scripts/split-call-tables.py
All header names in the datavzrd report (but also tables) have been set to lowercase making the report more readable but is also more intuitive adding changes to the workflow.
=> feat!: use lowercase for all header names in report tables

.test/config-giab/config.yaml, config/config.yaml, workflow/envs/vep.yaml, workflow/rules/annotation.smk, workflow/rules/ref.smk
The current workflow is using snakemake-wrappers for loading VEP=108 while the config-file sets the reference to v105.
To avoid any issues annotating variants I suggest to update the config-file and the snakemake-wrappers to the latest version being v109.
=> fix: fix mixed up VEP and VEP-cache versions

workflow/rules/candidate_calling.smk, workflow/rules/ref.smk, workflow/scripts/split-call-tables.py
As workflows like dna-seq-mtb come with several callsets each being split by low and high allele frequency the final datavzrd report becomes cluttered.
Instead of creating two separate callssets we could create a single one by adding additional binned allele frequency columns(binned into `low`, `medium` and `high`). This allows to sort variants by their AF showing variants with a high frequency on top of the report.
While this PR is just a preparation and the sorting needs to be defined in the callset configuration I would like to discuss if this implementation can be improved. Currently we have a distinct allele frequency for each sample (e.g. tumor and normal) resulting in a corresponding binned AF column.
As we have use predefined callsets in the `dna-seq-mtb` workflow we also need to …
=> feat: add binned vaf column for sorting by allele frequency

workflow/resources/datavzrd/data_observations.js, workflow/resources/datavzrd/spec_observations.json
In the observation plots reference alleles are currently not being rendered as they the field has been renamed to `Ref` but is still called as `Reference`.
It also looks like high and low mapping qualities were accidentally swapped.
=> fix: observations plots

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
In some cases rendering the datavzrd report fails as the input datatable might not contain an `id` column.
This happens when splitting tables into noncoding and coding as empty columns are being dropped.
=> fix: set id optional

.github/workflows/main.yml, workflow/rules/annotation.smk, workflow/rules/candidate_calling.smk, workflow/rules/common.smk
These changes address multiple features/issues.
- freebayes-parallel was failing. This has been fixed by updating to the latest snakemake wrapper
- raw fastq files which already were trimmed on creation were not supported. Now, if no adapter is set in the `units.tsv` trimming with cutadapt will be skipped
- gnomAD allele frequency column was added to the datavzrd report
=> feat: Handle trimmed fastqs plus additional fixes

.test/config-chm-eval/config.yaml, .test/config-giab/config.yaml, .test/config-no-candidate-filtering/config.yaml, .test/config-simple/config.yaml, .test/config-sra/config.yaml, .test/config-target-regions/config.yaml, .test/config-target-regions/config_multiple_beds.yaml, .test/config_primers/config.yaml, config/config.yaml, workflow/rules/annotation.smk, workflow/rules/common.smk, workflow/schemas/config.schema.yaml
We have a use case, where we want to use gnomAD population frequencies of variants to filter out common variants BEFORE running varlociraptor. For this, we need to be able to customize the vep flags (and potentially plugins in the future) used for annotating candidate calls before candidate call filtering. This PR introduces this.
=> feat!: make annotations for candidate variant filtering configurable

workflow/rules/mapping.smk
a `mem_gb` specification plus a `default-resources:` specification of `mem_mb` for a cluster system leads to multiple distinct resource definitions that can get confused -- so we should just stick to the standard `mem_mb` here
=> fix: switch mem_gb to mem_mb

workflow/rules/common.smk, workflow/rules/mapping.smk
Not really a fix but a semantical correction. The function `sample_has_umis` returns `false` if a sample contains umis.
As this implementation was consistently confused the workflow ran correctly.
Still, to prevent any mistakes in the future it should be changed.
=> fix: sample has umis

workflow/rules/qc.smk
The memory parsing fix for the wrapper was introduced in `snakemake-wrapper-utils` here:
https://github.com/snakemake/snakemake-wrapper-utils/pull/34
=> fix: update fastqc wrapper to `v1.10.0` to include memory parsing fix

.test/config-chm-eval/config.yaml, .test/config-giab/config.yaml, .test/config-no-candidate-filtering/config.yaml, .test/config-simple/config.yaml, .test/config-sra/config.yaml, .test/config-target-regions/config.yaml, .test/config-target-regions/config_multiple_beds.yaml, .test/config_primers/config.yaml, config/config.yaml, workflow/resources/datavzrd/gene-coverage-template.datavzrd.yaml, workflow/rules/common.smk, workflow/rules/datavzrd.smk, workflow/rules/ref.smk, workflow/rules/regions.smk, workflow/schemas/config.schema.yaml, workflow/scripts/coverage_table.py, workflow/scripts/transform_gene_regions.py
This adds an additional datavzrd report showing the gene mean gene coverages per sample group-wise.
While the annotation file previously was a gzip file we now directly output a plain gtf file.
This must be done for fusion calling anyway as zipped files are not supported.
=> feat: gene coverage report

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/datavzrd.smk
After tick plots have been replaced by heatmaps in a previous PR these are once again replaced by new tick plots with color mapping introduced in the latest datavzrd version.
=> feat: colored tick plots in datavzrd report

workflow/rules/common.smk
Also provide helpful error if the extracted series contains multiple distinct values.
Previously, these did not get triggered by our tests, because we apparently don't yet test the combination of having UMIs or primers specified AND having a sample repeated. So I'll also try extending one of the simpler tests accordingly on this PR.
=> fix: unique values when extracting samples column for repeated samples (in multiple groups)

workflow/envs/fgbio.yaml, workflow/rules/common.smk, workflow/rules/mapping.smk
For large samples `fgbio AnnotateBamWithUmis` fails due to memory issues.
This happens as fgbio loads the fully uncompressed UMI fastq file into memory.
We already tried to fix this in a previous PR (https://github.com/snakemake-workflows/dna-seq-varlociraptor/pull/262) by dynamically assigning more memory based on input file size.
Still this does not suffice in many cases.
To get this fixed fgbio suggests a [best practice](https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#phase-1-fastq---grouped-bam) where raw reads are transformed into unmapped bam files while annotating UMIs at the same time.
In our case this is not feasible as reads need to be adapter trimmed by cutadapt first.
But in case of Qiagen reads the UMI lies in front of the adapter …
=> feat: reduce fgbio memory usage

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/common.smk, workflow/rules/filtering.smk
The fusion calling workflow fails in case of candidate calls being filtered.
This happens as `vembrane filter` does not keep entries coordinate sorted but groups records by fusion mates.
Therefore `varlociraptor preprocess` fails as it expects coordinate sorted input.
Further a minor change to the variant calling datavzrd report has been made.
The report now shows HGVSc instead of HGVSg values. HGVSg values are still used for Genome Nexus linkouts but the entry itself is now hidden.
=> fix: fusion candidate filtering and add HGVSc to variant datavzrd report

workflow/resources/datavzrd/clinical_significance.js, workflow/resources/datavzrd/linkouts.js, workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml, workflow/rules/datavzrd.smk
This PR adds improved visualization for clinical significance.
=> feat: Add improved visualization for clinical significance

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
This avoids downstream errors when checking for emptyness.
=> fix: always use the same type for label list in datavzrd config

workflow/resources/datavzrd/variant-calls-template.datavzrd.yaml
This fixes the type error originating from rendering group annotations in datavzrd config.
=> fix: use list type for group annotations in datavzrd config

.test/config-no-candidate-filtering/config.yaml, config/config.yaml
This has tripped up multiple people by now, so let's fix the example in the standard `config/config.yaml` that everybody gets upon module-based deployment.
=> fix: make the `aux-files` example use the existing `ANN` field `SYMBOL`

workflow/rules/mapping.smk
In the previous PR sorting for reads mapped by vg was introduced.
Those changes did not fully consider sorting of reads without duplicates.
This is now reflected by generalizing and renaming the `sort_duplicates` rule.
=> fix: generalize sorting for pangenome mapped reads

workflow/scripts/split-call-tables.py
pandas `read_csv` has a bunch of default values it parses into `NaN` automatically, among them `NA`:
https://pandas.pydata.org/pandas-docs/version/2.1/reference/api/pandas.read_csv.html#pandas.read_csv
But in our context, this can be a valid reference allele (`REF`) with an unknown nucleotide in the reference sequence at the first position. So we don't want this parsing. Also, `vembrane table` prints missing values as empty column entries, so the empty string should probably be the only automatic parsing to `NaN`.
=> fix: avoid mis-parsing `NA` reference (`REF`) alleles in `split-call-tables.py`
